class Solution:
    """
    Grade[Medium]
    Topics[Hash Table, String, Bit Manipulation, Sorting]

    You are given two strings s and t.

    String t is generated by random shuffling string s and then add one more letter at a random position.

    Return the letter that was added to t.
    """
    def findTheDifference(self, s: str, t: str) -> str:
        """
        Time complexity: O(n)
        Space complexity: O(1)
        """
        return chr(sum([ord(char) for char in t]) - sum([ord(char) for char in s]))